### ISSUE TITLE
Using http protocol to `wiki.tournesol.app` is insecure from a user perspective

### ISSUE THREAD

**Issue by alban-auzeill** [tournesol-app/tournesol-frontend#2]
`https` should be used here:
https://github.com/tournesol-app/tournesol-frontend/blob/a61339b44676bf4f96ddeeb8a348fdff6fc46cd0/src/components/Home.js#L175

**Comment by jstainer-kleis** [comment]
Thanks for the heads-up.
The reverse proxy redirects http to https anyway though and the code base has been rebooted from scratch, I consequently close this issue.
